// テンプレートカード（初級用の基本英文）

export interface TemplateCard {
  prompt_jp: string;
  target_en: string;
}

export const basicTemplates: TemplateCard[] = [
  { prompt_jp: "こんにちは。", target_en: "Hello." },
  { prompt_jp: "お元気ですか？", target_en: "How are you?" },
  { prompt_jp: "元気です。", target_en: "I'm fine." },
  { prompt_jp: "ありがとうございます。", target_en: "Thank you very much." },
  { prompt_jp: "どういたしまして。", target_en: "You're welcome." },
  { prompt_jp: "すみません。", target_en: "Excuse me." },
  { prompt_jp: "ごめんなさい。", target_en: "I'm sorry." },
  { prompt_jp: "お名前は何ですか？", target_en: "What's your name?" },
  { prompt_jp: "私の名前は太郎です。", target_en: "My name is Taro." },
  { prompt_jp: "はじめまして。", target_en: "Nice to meet you." },
  { prompt_jp: "よろしくお願いします。", target_en: "Nice to meet you." },
  { prompt_jp: "どこに住んでいますか？", target_en: "Where do you live?" },
  { prompt_jp: "東京に住んでいます。", target_en: "I live in Tokyo." },
  { prompt_jp: "何歳ですか？", target_en: "How old are you?" },
  { prompt_jp: "20歳です。", target_en: "I'm twenty years old." },
  { prompt_jp: "何をしていますか？", target_en: "What do you do?" },
  { prompt_jp: "学生です。", target_en: "I'm a student." },
  { prompt_jp: "会社員です。", target_en: "I'm an office worker." },
  { prompt_jp: "英語を勉強しています。", target_en: "I'm studying English." },
  { prompt_jp: "英語が好きです。", target_en: "I like English." },
  { prompt_jp: "今日はいい天気ですね。", target_en: "It's a nice day today." },
  { prompt_jp: "寒いですね。", target_en: "It's cold, isn't it?" },
  { prompt_jp: "暑いですね。", target_en: "It's hot, isn't it?" },
  { prompt_jp: "何時ですか？", target_en: "What time is it?" },
  { prompt_jp: "3時です。", target_en: "It's three o'clock." },
  { prompt_jp: "お腹が空きました。", target_en: "I'm hungry." },
  { prompt_jp: "のどが渇きました。", target_en: "I'm thirsty." },
  { prompt_jp: "疲れました。", target_en: "I'm tired." },
  { prompt_jp: "元気です。", target_en: "I'm fine." },
  { prompt_jp: "どこに行きますか？", target_en: "Where are you going?" },
  { prompt_jp: "学校に行きます。", target_en: "I'm going to school." },
  { prompt_jp: "家に帰ります。", target_en: "I'm going home." },
  { prompt_jp: "何を食べますか？", target_en: "What are you going to eat?" },
  { prompt_jp: "ラーメンを食べます。", target_en: "I'm going to eat ramen." },
  { prompt_jp: "コーヒーを飲みます。", target_en: "I'm going to drink coffee." },
  { prompt_jp: "本を読みます。", target_en: "I read books." },
  { prompt_jp: "音楽を聞きます。", target_en: "I listen to music." },
  { prompt_jp: "テレビを見ます。", target_en: "I watch TV." },
  { prompt_jp: "映画を見ます。", target_en: "I watch movies." },
  { prompt_jp: "友達と遊びます。", target_en: "I play with my friends." },
  { prompt_jp: "スポーツをします。", target_en: "I play sports." },
  { prompt_jp: "買い物に行きます。", target_en: "I'm going shopping." },
  { prompt_jp: "お金がありません。", target_en: "I don't have money." },
  { prompt_jp: "時間がありません。", target_en: "I don't have time." },
  { prompt_jp: "わかりました。", target_en: "I understand." },
  { prompt_jp: "わかりません。", target_en: "I don't understand." },
  { prompt_jp: "もう一度言ってください。", target_en: "Could you say that again?" },
  { prompt_jp: "ゆっくり話してください。", target_en: "Could you speak slowly?" },
  { prompt_jp: "英語で何と言いますか？", target_en: "How do you say this in English?" },
  { prompt_jp: "これは何ですか？", target_en: "What is this?" },
  { prompt_jp: "それは本です。", target_en: "That's a book." },
  { prompt_jp: "いくらですか？", target_en: "How much is it?" },
  { prompt_jp: "1000円です。", target_en: "It's 1000 yen." },
  { prompt_jp: "これをください。", target_en: "I'll take this." },
  { prompt_jp: "お会計お願いします。", target_en: "Check, please." },
  { prompt_jp: "クレジットカードで払えますか？", target_en: "Can I pay by credit card?" },
  { prompt_jp: "現金で払います。", target_en: "I'll pay in cash." },
];

